### PR TITLE
migrated recontruct_areacello to upstream_stash

### PR DESCRIPTION
**Pull request by sditkovsky**
started an `upstream_stash.py` file to place functions that will eventually be elsewhere. 

For the `reconstruct_areacello()` function, I was having trouble making a test array with bounds, so I just tested the simplified case of calculating directly from lat/lon. For the simplified case, getting the latitude spacing is tricky for one end of the domain, so that bit is sort of fudged at this point.

### CODE REVIEW

**Comment by jbusecke** [comment]
I am thinking if we actually need this feature at all? Is this just specific to WOA? In that case I might take back my previous comment and leave it in the `dataset.py` module for now and make a note to replace this with a more general function some time in the future.

If this is needed for the cmip data I think we should try to not use it anymore. In my experience most of the models do have area input. Could you see if you can use the new [cmip6_pp metrics parser](https://cmip6-preprocessing.readthedocs.io/en/latest/postprocessing.html#Handling-grid-metrics-in-CMIP6) and eliminate the need to reconstruct stuff altogether?

**Comment by sditkovsky** [comment]
Do you think that the cmip6_pp functions could work for the WOA dataset as well?

**Comment by sditkovsky** [comment]
Okay, from looking at the metric parser docs, it does seem like the reconstruction of area from dx, dy will only apply to observations. But also that we might still need that reconstruction function for observations

**Comment by jbusecke** [comment]
> Do you think that the cmip6_pp functions could work for the WOA dataset as well?

They totally should. I think that would be the cleanest option. I remember trying that and running into issue, but that was mostly time pressure. I think we can figure this out. I can take a crack at that next week. Does that work for you?

**Pull request closed without merging**
